[tool.black]
exclude = '''
/(
    \.git
    | \.eggs
    | \.*caches
    | \.tox
    | venv
    | _build
    | build
    | dist
)/
'''

# RUFF settings
[tool.ruff]
line-length = 120  # let black do line formatting
show-fixes = true
fix=true
cache-dir = ".caches/.ruff"

[tool.ruff.lint]
# see https://beta.ruff.rs/docs/rules/
select = ["A", "B", "C", "D", "E", "F", "I", "N", "UP", "PT", "W", "Q"]
ignore = ["D100", "D101", "D104", "D211", "D212"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I", "N", "UP", "PT", "W", "Q"]
# fix = true
unfixable = []


[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D"]
"gtk_indicator.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["tenma_serial"]

# MYPY settings
[tool.mypy]
ignore_missing_imports = true
strict = true
cache_dir = ".caches/.mypy"
exclude = ["venv", "tests", "examples"]
explicit_package_bases = true